/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var electrious_models_file_pb = require('../../../../electrious/models/file_pb.js');
goog.object.extend(proto, electrious_models_file_pb);
var electrious_models_geometry_latlng_pb = require('../../../../electrious/models/geometry/latlng_pb.js');
goog.object.extend(proto, electrious_models_geometry_latlng_pb);
goog.exportSymbol('proto.electrious.workers.nodes.meshearth.Request', null, global);
goog.exportSymbol('proto.electrious.workers.nodes.meshearth.Request.Source', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.electrious.workers.nodes.meshearth.Request = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.electrious.workers.nodes.meshearth.Request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.electrious.workers.nodes.meshearth.Request.displayName = 'proto.electrious.workers.nodes.meshearth.Request';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.electrious.workers.nodes.meshearth.Request.prototype.toObject = function(opt_includeInstance) {
  return proto.electrious.workers.nodes.meshearth.Request.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.electrious.workers.nodes.meshearth.Request} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.workers.nodes.meshearth.Request.toObject = function(includeInstance, msg) {
  var obj = {
    latlng: (f = msg.getLatlng()) && electrious_models_geometry_latlng_pb.LatLng.toObject(includeInstance, f),
    source: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.electrious.workers.nodes.meshearth.Request}
 */
proto.electrious.workers.nodes.meshearth.Request.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.electrious.workers.nodes.meshearth.Request;
  return proto.electrious.workers.nodes.meshearth.Request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.electrious.workers.nodes.meshearth.Request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.electrious.workers.nodes.meshearth.Request}
 */
proto.electrious.workers.nodes.meshearth.Request.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new electrious_models_geometry_latlng_pb.LatLng;
      reader.readMessage(value,electrious_models_geometry_latlng_pb.LatLng.deserializeBinaryFromReader);
      msg.setLatlng(value);
      break;
    case 2:
      var value = /** @type {!proto.electrious.workers.nodes.meshearth.Request.Source} */ (reader.readEnum());
      msg.setSource(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.electrious.workers.nodes.meshearth.Request.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.electrious.workers.nodes.meshearth.Request.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.electrious.workers.nodes.meshearth.Request} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.workers.nodes.meshearth.Request.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLatlng();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      electrious_models_geometry_latlng_pb.LatLng.serializeBinaryToWriter
    );
  }
  f = message.getSource();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.electrious.workers.nodes.meshearth.Request.Source = {
  SOURCE_INVALID: 0,
  SOURCE_EARTH: 1,
  SOURCE_FLYOVER: 2
};

/**
 * optional electrious.models.geometry.LatLng latlng = 1;
 * @return {?proto.electrious.models.geometry.LatLng}
 */
proto.electrious.workers.nodes.meshearth.Request.prototype.getLatlng = function() {
  return /** @type{?proto.electrious.models.geometry.LatLng} */ (
    jspb.Message.getWrapperField(this, electrious_models_geometry_latlng_pb.LatLng, 1));
};


/** @param {?proto.electrious.models.geometry.LatLng|undefined} value */
proto.electrious.workers.nodes.meshearth.Request.prototype.setLatlng = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.electrious.workers.nodes.meshearth.Request.prototype.clearLatlng = function() {
  this.setLatlng(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.electrious.workers.nodes.meshearth.Request.prototype.hasLatlng = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Source source = 2;
 * @return {!proto.electrious.workers.nodes.meshearth.Request.Source}
 */
proto.electrious.workers.nodes.meshearth.Request.prototype.getSource = function() {
  return /** @type {!proto.electrious.workers.nodes.meshearth.Request.Source} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.electrious.workers.nodes.meshearth.Request.Source} value */
proto.electrious.workers.nodes.meshearth.Request.prototype.setSource = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


goog.object.extend(exports, proto.electrious.workers.nodes.meshearth);
