/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var electrious_models_racking_component_pb = require('../../electrious/models/racking/component_pb.js');
goog.object.extend(proto, electrious_models_racking_component_pb);
var electrious_models_racking_kind_pb = require('../../electrious/models/racking/kind_pb.js');
goog.object.extend(proto, electrious_models_racking_kind_pb);
var electrious_models_racking_mount_pb = require('../../electrious/models/racking/mount_pb.js');
goog.object.extend(proto, electrious_models_racking_mount_pb);
var electrious_models_racking_rafter_pb = require('../../electrious/models/racking/rafter_pb.js');
goog.object.extend(proto, electrious_models_racking_rafter_pb);
var electrious_models_racking_roof_parameter_pb = require('../../electrious/models/racking/roof_parameter_pb.js');
goog.object.extend(proto, electrious_models_racking_roof_parameter_pb);
goog.exportSymbol('proto.electrious.models.Racking', null, global);
goog.exportSymbol('proto.electrious.models.RackingSystem', null, global);
goog.exportSymbol('proto.electrious.models.RoofRacking', null, global);
goog.exportSymbol('proto.electrious.models.RoofRackingResult', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.electrious.models.RoofRacking = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.electrious.models.RoofRacking.repeatedFields_, null);
};
goog.inherits(proto.electrious.models.RoofRacking, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.electrious.models.RoofRacking.displayName = 'proto.electrious.models.RoofRacking';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.electrious.models.Racking = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.electrious.models.Racking, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.electrious.models.Racking.displayName = 'proto.electrious.models.Racking';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.electrious.models.RoofRackingResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.electrious.models.RoofRackingResult.repeatedFields_, null);
};
goog.inherits(proto.electrious.models.RoofRackingResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.electrious.models.RoofRackingResult.displayName = 'proto.electrious.models.RoofRackingResult';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.electrious.models.RackingSystem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.electrious.models.RackingSystem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.electrious.models.RackingSystem.displayName = 'proto.electrious.models.RackingSystem';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.electrious.models.RoofRacking.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.electrious.models.RoofRacking.prototype.toObject = function(opt_includeInstance) {
  return proto.electrious.models.RoofRacking.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.electrious.models.RoofRacking} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.RoofRacking.toObject = function(includeInstance, msg) {
  var obj = {
    raftersList: jspb.Message.toObjectList(msg.getRaftersList(),
    electrious_models_racking_rafter_pb.Rafter.toObject, includeInstance),
    mountSpacing: jspb.Message.getFieldWithDefault(msg, 2, 0),
    rafterSpacing: jspb.Message.getFieldWithDefault(msg, 3, 0),
    componentsMap: (f = msg.getComponentsMap()) ? f.toObject(includeInstance, proto.electrious.models.racking.Component.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.electrious.models.RoofRacking}
 */
proto.electrious.models.RoofRacking.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.electrious.models.RoofRacking;
  return proto.electrious.models.RoofRacking.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.electrious.models.RoofRacking} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.electrious.models.RoofRacking}
 */
proto.electrious.models.RoofRacking.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new electrious_models_racking_rafter_pb.Rafter;
      reader.readMessage(value,electrious_models_racking_rafter_pb.Rafter.deserializeBinaryFromReader);
      msg.addRafters(value);
      break;
    case 2:
      var value = /** @type {!proto.electrious.models.racking.Mount.Spacing} */ (reader.readEnum());
      msg.setMountSpacing(value);
      break;
    case 3:
      var value = /** @type {!proto.electrious.models.racking.Rafter.Spacing} */ (reader.readEnum());
      msg.setRafterSpacing(value);
      break;
    case 4:
      var value = msg.getComponentsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readUint64, jspb.BinaryReader.prototype.readMessage, proto.electrious.models.racking.Component.deserializeBinaryFromReader, 0);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.electrious.models.RoofRacking.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.electrious.models.RoofRacking.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.electrious.models.RoofRacking} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.RoofRacking.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRaftersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      electrious_models_racking_rafter_pb.Rafter.serializeBinaryToWriter
    );
  }
  f = message.getMountSpacing();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getRafterSpacing();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getComponentsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeUint64, jspb.BinaryWriter.prototype.writeMessage, proto.electrious.models.racking.Component.serializeBinaryToWriter);
  }
};


/**
 * repeated racking.Rafter rafters = 1;
 * @return {!Array<!proto.electrious.models.racking.Rafter>}
 */
proto.electrious.models.RoofRacking.prototype.getRaftersList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Rafter>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_rafter_pb.Rafter, 1));
};


/** @param {!Array<!proto.electrious.models.racking.Rafter>} value */
proto.electrious.models.RoofRacking.prototype.setRaftersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.electrious.models.racking.Rafter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Rafter}
 */
proto.electrious.models.RoofRacking.prototype.addRafters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.electrious.models.racking.Rafter, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.RoofRacking.prototype.clearRaftersList = function() {
  this.setRaftersList([]);
};


/**
 * optional racking.Mount.Spacing mount_spacing = 2;
 * @return {!proto.electrious.models.racking.Mount.Spacing}
 */
proto.electrious.models.RoofRacking.prototype.getMountSpacing = function() {
  return /** @type {!proto.electrious.models.racking.Mount.Spacing} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.electrious.models.racking.Mount.Spacing} value */
proto.electrious.models.RoofRacking.prototype.setMountSpacing = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional racking.Rafter.Spacing rafter_spacing = 3;
 * @return {!proto.electrious.models.racking.Rafter.Spacing}
 */
proto.electrious.models.RoofRacking.prototype.getRafterSpacing = function() {
  return /** @type {!proto.electrious.models.racking.Rafter.Spacing} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.electrious.models.racking.Rafter.Spacing} value */
proto.electrious.models.RoofRacking.prototype.setRafterSpacing = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * map<uint64, racking.Component> components = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.electrious.models.racking.Component>}
 */
proto.electrious.models.RoofRacking.prototype.getComponentsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.electrious.models.racking.Component>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      proto.electrious.models.racking.Component));
};


/**
 * Clears values from the map. The map will be non-null.
 */
proto.electrious.models.RoofRacking.prototype.clearComponentsMap = function() {
  this.getComponentsMap().clear();
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.electrious.models.Racking.prototype.toObject = function(opt_includeInstance) {
  return proto.electrious.models.Racking.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.electrious.models.Racking} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.Racking.toObject = function(includeInstance, msg) {
  var obj = {
    kind: jspb.Message.getFieldWithDefault(msg, 1, 0),
    roofRackingsMap: (f = msg.getRoofRackingsMap()) ? f.toObject(includeInstance, proto.electrious.models.RoofRacking.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.electrious.models.Racking}
 */
proto.electrious.models.Racking.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.electrious.models.Racking;
  return proto.electrious.models.Racking.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.electrious.models.Racking} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.electrious.models.Racking}
 */
proto.electrious.models.Racking.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.electrious.models.racking.Kind} */ (reader.readEnum());
      msg.setKind(value);
      break;
    case 2:
      var value = msg.getRoofRackingsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.electrious.models.RoofRacking.deserializeBinaryFromReader, "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.electrious.models.Racking.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.electrious.models.Racking.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.electrious.models.Racking} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.Racking.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKind();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getRoofRackingsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.electrious.models.RoofRacking.serializeBinaryToWriter);
  }
};


/**
 * optional racking.Kind kind = 1;
 * @return {!proto.electrious.models.racking.Kind}
 */
proto.electrious.models.Racking.prototype.getKind = function() {
  return /** @type {!proto.electrious.models.racking.Kind} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.electrious.models.racking.Kind} value */
proto.electrious.models.Racking.prototype.setKind = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * map<string, RoofRacking> roof_rackings = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.electrious.models.RoofRacking>}
 */
proto.electrious.models.Racking.prototype.getRoofRackingsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.electrious.models.RoofRacking>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.electrious.models.RoofRacking));
};


/**
 * Clears values from the map. The map will be non-null.
 */
proto.electrious.models.Racking.prototype.clearRoofRackingsMap = function() {
  this.getRoofRackingsMap().clear();
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.electrious.models.RoofRackingResult.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.electrious.models.RoofRackingResult.prototype.toObject = function(opt_includeInstance) {
  return proto.electrious.models.RoofRackingResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.electrious.models.RoofRackingResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.RoofRackingResult.toObject = function(includeInstance, msg) {
  var obj = {
    kind: jspb.Message.getFieldWithDefault(msg, 1, 0),
    raftersList: jspb.Message.toObjectList(msg.getRaftersList(),
    electrious_models_racking_rafter_pb.Rafter.toObject, includeInstance),
    params: (f = msg.getParams()) && electrious_models_racking_roof_parameter_pb.RoofParameter.toObject(includeInstance, f),
    componentsMap: (f = msg.getComponentsMap()) ? f.toObject(includeInstance, proto.electrious.models.racking.Component.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.electrious.models.RoofRackingResult}
 */
proto.electrious.models.RoofRackingResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.electrious.models.RoofRackingResult;
  return proto.electrious.models.RoofRackingResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.electrious.models.RoofRackingResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.electrious.models.RoofRackingResult}
 */
proto.electrious.models.RoofRackingResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.electrious.models.racking.Kind} */ (reader.readEnum());
      msg.setKind(value);
      break;
    case 2:
      var value = new electrious_models_racking_rafter_pb.Rafter;
      reader.readMessage(value,electrious_models_racking_rafter_pb.Rafter.deserializeBinaryFromReader);
      msg.addRafters(value);
      break;
    case 3:
      var value = new electrious_models_racking_roof_parameter_pb.RoofParameter;
      reader.readMessage(value,electrious_models_racking_roof_parameter_pb.RoofParameter.deserializeBinaryFromReader);
      msg.setParams(value);
      break;
    case 4:
      var value = msg.getComponentsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readUint64, jspb.BinaryReader.prototype.readMessage, proto.electrious.models.racking.Component.deserializeBinaryFromReader, 0);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.electrious.models.RoofRackingResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.electrious.models.RoofRackingResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.electrious.models.RoofRackingResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.RoofRackingResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKind();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getRaftersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      electrious_models_racking_rafter_pb.Rafter.serializeBinaryToWriter
    );
  }
  f = message.getParams();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      electrious_models_racking_roof_parameter_pb.RoofParameter.serializeBinaryToWriter
    );
  }
  f = message.getComponentsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeUint64, jspb.BinaryWriter.prototype.writeMessage, proto.electrious.models.racking.Component.serializeBinaryToWriter);
  }
};


/**
 * optional racking.Kind kind = 1;
 * @return {!proto.electrious.models.racking.Kind}
 */
proto.electrious.models.RoofRackingResult.prototype.getKind = function() {
  return /** @type {!proto.electrious.models.racking.Kind} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.electrious.models.racking.Kind} value */
proto.electrious.models.RoofRackingResult.prototype.setKind = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * repeated racking.Rafter rafters = 2;
 * @return {!Array<!proto.electrious.models.racking.Rafter>}
 */
proto.electrious.models.RoofRackingResult.prototype.getRaftersList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Rafter>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_rafter_pb.Rafter, 2));
};


/** @param {!Array<!proto.electrious.models.racking.Rafter>} value */
proto.electrious.models.RoofRackingResult.prototype.setRaftersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.electrious.models.racking.Rafter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Rafter}
 */
proto.electrious.models.RoofRackingResult.prototype.addRafters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.electrious.models.racking.Rafter, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.RoofRackingResult.prototype.clearRaftersList = function() {
  this.setRaftersList([]);
};


/**
 * optional racking.RoofParameter params = 3;
 * @return {?proto.electrious.models.racking.RoofParameter}
 */
proto.electrious.models.RoofRackingResult.prototype.getParams = function() {
  return /** @type{?proto.electrious.models.racking.RoofParameter} */ (
    jspb.Message.getWrapperField(this, electrious_models_racking_roof_parameter_pb.RoofParameter, 3));
};


/** @param {?proto.electrious.models.racking.RoofParameter|undefined} value */
proto.electrious.models.RoofRackingResult.prototype.setParams = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.electrious.models.RoofRackingResult.prototype.clearParams = function() {
  this.setParams(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.electrious.models.RoofRackingResult.prototype.hasParams = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * map<uint64, racking.Component> components = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.electrious.models.racking.Component>}
 */
proto.electrious.models.RoofRackingResult.prototype.getComponentsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.electrious.models.racking.Component>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      proto.electrious.models.racking.Component));
};


/**
 * Clears values from the map. The map will be non-null.
 */
proto.electrious.models.RoofRackingResult.prototype.clearComponentsMap = function() {
  this.getComponentsMap().clear();
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.electrious.models.RackingSystem.prototype.toObject = function(opt_includeInstance) {
  return proto.electrious.models.RackingSystem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.electrious.models.RackingSystem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.RackingSystem.toObject = function(includeInstance, msg) {
  var obj = {
    roofRackingsMap: (f = msg.getRoofRackingsMap()) ? f.toObject(includeInstance, proto.electrious.models.RoofRackingResult.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.electrious.models.RackingSystem}
 */
proto.electrious.models.RackingSystem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.electrious.models.RackingSystem;
  return proto.electrious.models.RackingSystem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.electrious.models.RackingSystem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.electrious.models.RackingSystem}
 */
proto.electrious.models.RackingSystem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getRoofRackingsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.electrious.models.RoofRackingResult.deserializeBinaryFromReader, "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.electrious.models.RackingSystem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.electrious.models.RackingSystem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.electrious.models.RackingSystem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.RackingSystem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRoofRackingsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.electrious.models.RoofRackingResult.serializeBinaryToWriter);
  }
};


/**
 * map<string, RoofRackingResult> roof_rackings = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.electrious.models.RoofRackingResult>}
 */
proto.electrious.models.RackingSystem.prototype.getRoofRackingsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.electrious.models.RoofRackingResult>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      proto.electrious.models.RoofRackingResult));
};


/**
 * Clears values from the map. The map will be non-null.
 */
proto.electrious.models.RackingSystem.prototype.clearRoofRackingsMap = function() {
  this.getRoofRackingsMap().clear();
};


goog.object.extend(exports, proto.electrious.models);
