/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var electrious_models_racking_block_pb = require('../../../electrious/models/racking/block_pb.js');
goog.object.extend(proto, electrious_models_racking_block_pb);
var electrious_models_racking_bridge_pb = require('../../../electrious/models/racking/bridge_pb.js');
goog.object.extend(proto, electrious_models_racking_bridge_pb);
var electrious_models_racking_chassis_pb = require('../../../electrious/models/racking/chassis_pb.js');
goog.object.extend(proto, electrious_models_racking_chassis_pb);
var electrious_models_racking_clamp_pb = require('../../../electrious/models/racking/clamp_pb.js');
goog.object.extend(proto, electrious_models_racking_clamp_pb);
var electrious_models_racking_endcap_pb = require('../../../electrious/models/racking/endcap_pb.js');
goog.object.extend(proto, electrious_models_racking_endcap_pb);
var electrious_models_racking_flash_pb = require('../../../electrious/models/racking/flash_pb.js');
goog.object.extend(proto, electrious_models_racking_flash_pb);
var electrious_models_racking_hood_pb = require('../../../electrious/models/racking/hood_pb.js');
goog.object.extend(proto, electrious_models_racking_hood_pb);
var electrious_models_racking_lfoot_pb = require('../../../electrious/models/racking/lfoot_pb.js');
goog.object.extend(proto, electrious_models_racking_lfoot_pb);
var electrious_models_racking_mount_pb = require('../../../electrious/models/racking/mount_pb.js');
goog.object.extend(proto, electrious_models_racking_mount_pb);
var electrious_models_racking_qbasemount_pb = require('../../../electrious/models/racking/qbasemount_pb.js');
goog.object.extend(proto, electrious_models_racking_qbasemount_pb);
var electrious_models_racking_rail_pb = require('../../../electrious/models/racking/rail_pb.js');
goog.object.extend(proto, electrious_models_racking_rail_pb);
var electrious_models_racking_skirt_pb = require('../../../electrious/models/racking/skirt_pb.js');
goog.object.extend(proto, electrious_models_racking_skirt_pb);
var electrious_models_racking_splice_pb = require('../../../electrious/models/racking/splice_pb.js');
goog.object.extend(proto, electrious_models_racking_splice_pb);
var electrious_models_racking_stopper_pb = require('../../../electrious/models/racking/stopper_pb.js');
goog.object.extend(proto, electrious_models_racking_stopper_pb);
var electrious_models_racking_supportrail_pb = require('../../../electrious/models/racking/supportrail_pb.js');
goog.object.extend(proto, electrious_models_racking_supportrail_pb);
var electrious_models_racking_tiltleg_pb = require('../../../electrious/models/racking/tiltleg_pb.js');
goog.object.extend(proto, electrious_models_racking_tiltleg_pb);
goog.exportSymbol('proto.electrious.models.racking.BallastComponent', null, global);
goog.exportSymbol('proto.electrious.models.racking.Component', null, global);
goog.exportSymbol('proto.electrious.models.racking.GAFComponent', null, global);
goog.exportSymbol('proto.electrious.models.racking.RailComponent', null, global);
goog.exportSymbol('proto.electrious.models.racking.RailFlatComponent', null, global);
goog.exportSymbol('proto.electrious.models.racking.RailFreeComponent', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.electrious.models.racking.Component = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.electrious.models.racking.Component.oneofGroups_);
};
goog.inherits(proto.electrious.models.racking.Component, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.electrious.models.racking.Component.displayName = 'proto.electrious.models.racking.Component';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.electrious.models.racking.RailComponent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.electrious.models.racking.RailComponent.repeatedFields_, null);
};
goog.inherits(proto.electrious.models.racking.RailComponent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.electrious.models.racking.RailComponent.displayName = 'proto.electrious.models.racking.RailComponent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.electrious.models.racking.RailFreeComponent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.electrious.models.racking.RailFreeComponent.repeatedFields_, null);
};
goog.inherits(proto.electrious.models.racking.RailFreeComponent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.electrious.models.racking.RailFreeComponent.displayName = 'proto.electrious.models.racking.RailFreeComponent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.electrious.models.racking.RailFlatComponent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.electrious.models.racking.RailFlatComponent.repeatedFields_, null);
};
goog.inherits(proto.electrious.models.racking.RailFlatComponent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.electrious.models.racking.RailFlatComponent.displayName = 'proto.electrious.models.racking.RailFlatComponent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.electrious.models.racking.BallastComponent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.electrious.models.racking.BallastComponent.repeatedFields_, null);
};
goog.inherits(proto.electrious.models.racking.BallastComponent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.electrious.models.racking.BallastComponent.displayName = 'proto.electrious.models.racking.BallastComponent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.electrious.models.racking.GAFComponent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.electrious.models.racking.GAFComponent.repeatedFields_, null);
};
goog.inherits(proto.electrious.models.racking.GAFComponent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.electrious.models.racking.GAFComponent.displayName = 'proto.electrious.models.racking.GAFComponent';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.electrious.models.racking.Component.oneofGroups_ = [[1,2,3,4,5]];

/**
 * @enum {number}
 */
proto.electrious.models.racking.Component.RdTypeCase = {
  RD_TYPE_NOT_SET: 0,
  RAIL: 1,
  RAIL_FREE: 2,
  RAIL_FLAT: 3,
  BALLAST: 4,
  GAF: 5
};

/**
 * @return {proto.electrious.models.racking.Component.RdTypeCase}
 */
proto.electrious.models.racking.Component.prototype.getRdTypeCase = function() {
  return /** @type {proto.electrious.models.racking.Component.RdTypeCase} */(jspb.Message.computeOneofCase(this, proto.electrious.models.racking.Component.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.electrious.models.racking.Component.prototype.toObject = function(opt_includeInstance) {
  return proto.electrious.models.racking.Component.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.electrious.models.racking.Component} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.racking.Component.toObject = function(includeInstance, msg) {
  var obj = {
    rail: (f = msg.getRail()) && proto.electrious.models.racking.RailComponent.toObject(includeInstance, f),
    railFree: (f = msg.getRailFree()) && proto.electrious.models.racking.RailFreeComponent.toObject(includeInstance, f),
    railFlat: (f = msg.getRailFlat()) && proto.electrious.models.racking.RailFlatComponent.toObject(includeInstance, f),
    ballast: (f = msg.getBallast()) && proto.electrious.models.racking.BallastComponent.toObject(includeInstance, f),
    gaf: (f = msg.getGaf()) && proto.electrious.models.racking.GAFComponent.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.electrious.models.racking.Component}
 */
proto.electrious.models.racking.Component.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.electrious.models.racking.Component;
  return proto.electrious.models.racking.Component.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.electrious.models.racking.Component} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.electrious.models.racking.Component}
 */
proto.electrious.models.racking.Component.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.electrious.models.racking.RailComponent;
      reader.readMessage(value,proto.electrious.models.racking.RailComponent.deserializeBinaryFromReader);
      msg.setRail(value);
      break;
    case 2:
      var value = new proto.electrious.models.racking.RailFreeComponent;
      reader.readMessage(value,proto.electrious.models.racking.RailFreeComponent.deserializeBinaryFromReader);
      msg.setRailFree(value);
      break;
    case 3:
      var value = new proto.electrious.models.racking.RailFlatComponent;
      reader.readMessage(value,proto.electrious.models.racking.RailFlatComponent.deserializeBinaryFromReader);
      msg.setRailFlat(value);
      break;
    case 4:
      var value = new proto.electrious.models.racking.BallastComponent;
      reader.readMessage(value,proto.electrious.models.racking.BallastComponent.deserializeBinaryFromReader);
      msg.setBallast(value);
      break;
    case 5:
      var value = new proto.electrious.models.racking.GAFComponent;
      reader.readMessage(value,proto.electrious.models.racking.GAFComponent.deserializeBinaryFromReader);
      msg.setGaf(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.electrious.models.racking.Component.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.electrious.models.racking.Component.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.electrious.models.racking.Component} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.racking.Component.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRail();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.electrious.models.racking.RailComponent.serializeBinaryToWriter
    );
  }
  f = message.getRailFree();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.electrious.models.racking.RailFreeComponent.serializeBinaryToWriter
    );
  }
  f = message.getRailFlat();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.electrious.models.racking.RailFlatComponent.serializeBinaryToWriter
    );
  }
  f = message.getBallast();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.electrious.models.racking.BallastComponent.serializeBinaryToWriter
    );
  }
  f = message.getGaf();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.electrious.models.racking.GAFComponent.serializeBinaryToWriter
    );
  }
};


/**
 * optional RailComponent rail = 1;
 * @return {?proto.electrious.models.racking.RailComponent}
 */
proto.electrious.models.racking.Component.prototype.getRail = function() {
  return /** @type{?proto.electrious.models.racking.RailComponent} */ (
    jspb.Message.getWrapperField(this, proto.electrious.models.racking.RailComponent, 1));
};


/** @param {?proto.electrious.models.racking.RailComponent|undefined} value */
proto.electrious.models.racking.Component.prototype.setRail = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.electrious.models.racking.Component.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.electrious.models.racking.Component.prototype.clearRail = function() {
  this.setRail(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.electrious.models.racking.Component.prototype.hasRail = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional RailFreeComponent rail_free = 2;
 * @return {?proto.electrious.models.racking.RailFreeComponent}
 */
proto.electrious.models.racking.Component.prototype.getRailFree = function() {
  return /** @type{?proto.electrious.models.racking.RailFreeComponent} */ (
    jspb.Message.getWrapperField(this, proto.electrious.models.racking.RailFreeComponent, 2));
};


/** @param {?proto.electrious.models.racking.RailFreeComponent|undefined} value */
proto.electrious.models.racking.Component.prototype.setRailFree = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.electrious.models.racking.Component.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.electrious.models.racking.Component.prototype.clearRailFree = function() {
  this.setRailFree(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.electrious.models.racking.Component.prototype.hasRailFree = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional RailFlatComponent rail_flat = 3;
 * @return {?proto.electrious.models.racking.RailFlatComponent}
 */
proto.electrious.models.racking.Component.prototype.getRailFlat = function() {
  return /** @type{?proto.electrious.models.racking.RailFlatComponent} */ (
    jspb.Message.getWrapperField(this, proto.electrious.models.racking.RailFlatComponent, 3));
};


/** @param {?proto.electrious.models.racking.RailFlatComponent|undefined} value */
proto.electrious.models.racking.Component.prototype.setRailFlat = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.electrious.models.racking.Component.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.electrious.models.racking.Component.prototype.clearRailFlat = function() {
  this.setRailFlat(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.electrious.models.racking.Component.prototype.hasRailFlat = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional BallastComponent ballast = 4;
 * @return {?proto.electrious.models.racking.BallastComponent}
 */
proto.electrious.models.racking.Component.prototype.getBallast = function() {
  return /** @type{?proto.electrious.models.racking.BallastComponent} */ (
    jspb.Message.getWrapperField(this, proto.electrious.models.racking.BallastComponent, 4));
};


/** @param {?proto.electrious.models.racking.BallastComponent|undefined} value */
proto.electrious.models.racking.Component.prototype.setBallast = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.electrious.models.racking.Component.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.electrious.models.racking.Component.prototype.clearBallast = function() {
  this.setBallast(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.electrious.models.racking.Component.prototype.hasBallast = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional GAFComponent gaf = 5;
 * @return {?proto.electrious.models.racking.GAFComponent}
 */
proto.electrious.models.racking.Component.prototype.getGaf = function() {
  return /** @type{?proto.electrious.models.racking.GAFComponent} */ (
    jspb.Message.getWrapperField(this, proto.electrious.models.racking.GAFComponent, 5));
};


/** @param {?proto.electrious.models.racking.GAFComponent|undefined} value */
proto.electrious.models.racking.Component.prototype.setGaf = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.electrious.models.racking.Component.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.electrious.models.racking.Component.prototype.clearGaf = function() {
  this.setGaf(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.electrious.models.racking.Component.prototype.hasGaf = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.electrious.models.racking.RailComponent.repeatedFields_ = [2,4,5,6,7,8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.electrious.models.racking.RailComponent.prototype.toObject = function(opt_includeInstance) {
  return proto.electrious.models.racking.RailComponent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.electrious.models.racking.RailComponent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.racking.RailComponent.toObject = function(includeInstance, msg) {
  var obj = {
    arrayNumber: jspb.Message.getFieldWithDefault(msg, 1, 0),
    railsList: jspb.Message.toObjectList(msg.getRailsList(),
    electrious_models_racking_rail_pb.Rail.toObject, includeInstance),
    fullRailsNum: jspb.Message.getFieldWithDefault(msg, 3, 0),
    splicesList: jspb.Message.toObjectList(msg.getSplicesList(),
    electrious_models_racking_splice_pb.Splice.toObject, includeInstance),
    flashesList: jspb.Message.toObjectList(msg.getFlashesList(),
    electrious_models_racking_flash_pb.Flash.toObject, includeInstance),
    lfeetList: jspb.Message.toObjectList(msg.getLfeetList(),
    electrious_models_racking_lfoot_pb.LFoot.toObject, includeInstance),
    clampsList: jspb.Message.toObjectList(msg.getClampsList(),
    electrious_models_racking_clamp_pb.Clamp.toObject, includeInstance),
    stoppersList: jspb.Message.toObjectList(msg.getStoppersList(),
    electrious_models_racking_stopper_pb.Stopper.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.electrious.models.racking.RailComponent}
 */
proto.electrious.models.racking.RailComponent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.electrious.models.racking.RailComponent;
  return proto.electrious.models.racking.RailComponent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.electrious.models.racking.RailComponent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.electrious.models.racking.RailComponent}
 */
proto.electrious.models.racking.RailComponent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setArrayNumber(value);
      break;
    case 2:
      var value = new electrious_models_racking_rail_pb.Rail;
      reader.readMessage(value,electrious_models_racking_rail_pb.Rail.deserializeBinaryFromReader);
      msg.addRails(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFullRailsNum(value);
      break;
    case 4:
      var value = new electrious_models_racking_splice_pb.Splice;
      reader.readMessage(value,electrious_models_racking_splice_pb.Splice.deserializeBinaryFromReader);
      msg.addSplices(value);
      break;
    case 5:
      var value = new electrious_models_racking_flash_pb.Flash;
      reader.readMessage(value,electrious_models_racking_flash_pb.Flash.deserializeBinaryFromReader);
      msg.addFlashes(value);
      break;
    case 6:
      var value = new electrious_models_racking_lfoot_pb.LFoot;
      reader.readMessage(value,electrious_models_racking_lfoot_pb.LFoot.deserializeBinaryFromReader);
      msg.addLfeet(value);
      break;
    case 7:
      var value = new electrious_models_racking_clamp_pb.Clamp;
      reader.readMessage(value,electrious_models_racking_clamp_pb.Clamp.deserializeBinaryFromReader);
      msg.addClamps(value);
      break;
    case 8:
      var value = new electrious_models_racking_stopper_pb.Stopper;
      reader.readMessage(value,electrious_models_racking_stopper_pb.Stopper.deserializeBinaryFromReader);
      msg.addStoppers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.electrious.models.racking.RailComponent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.electrious.models.racking.RailComponent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.electrious.models.racking.RailComponent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.racking.RailComponent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getArrayNumber();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getRailsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      electrious_models_racking_rail_pb.Rail.serializeBinaryToWriter
    );
  }
  f = message.getFullRailsNum();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getSplicesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      electrious_models_racking_splice_pb.Splice.serializeBinaryToWriter
    );
  }
  f = message.getFlashesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      electrious_models_racking_flash_pb.Flash.serializeBinaryToWriter
    );
  }
  f = message.getLfeetList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      electrious_models_racking_lfoot_pb.LFoot.serializeBinaryToWriter
    );
  }
  f = message.getClampsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      electrious_models_racking_clamp_pb.Clamp.serializeBinaryToWriter
    );
  }
  f = message.getStoppersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      electrious_models_racking_stopper_pb.Stopper.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 array_number = 1;
 * @return {number}
 */
proto.electrious.models.racking.RailComponent.prototype.getArrayNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.electrious.models.racking.RailComponent.prototype.setArrayNumber = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated Rail rails = 2;
 * @return {!Array<!proto.electrious.models.racking.Rail>}
 */
proto.electrious.models.racking.RailComponent.prototype.getRailsList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Rail>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_rail_pb.Rail, 2));
};


/** @param {!Array<!proto.electrious.models.racking.Rail>} value */
proto.electrious.models.racking.RailComponent.prototype.setRailsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.electrious.models.racking.Rail=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Rail}
 */
proto.electrious.models.racking.RailComponent.prototype.addRails = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.electrious.models.racking.Rail, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailComponent.prototype.clearRailsList = function() {
  this.setRailsList([]);
};


/**
 * optional int32 full_rails_num = 3;
 * @return {number}
 */
proto.electrious.models.racking.RailComponent.prototype.getFullRailsNum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.electrious.models.racking.RailComponent.prototype.setFullRailsNum = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated Splice splices = 4;
 * @return {!Array<!proto.electrious.models.racking.Splice>}
 */
proto.electrious.models.racking.RailComponent.prototype.getSplicesList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Splice>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_splice_pb.Splice, 4));
};


/** @param {!Array<!proto.electrious.models.racking.Splice>} value */
proto.electrious.models.racking.RailComponent.prototype.setSplicesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.electrious.models.racking.Splice=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Splice}
 */
proto.electrious.models.racking.RailComponent.prototype.addSplices = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.electrious.models.racking.Splice, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailComponent.prototype.clearSplicesList = function() {
  this.setSplicesList([]);
};


/**
 * repeated Flash flashes = 5;
 * @return {!Array<!proto.electrious.models.racking.Flash>}
 */
proto.electrious.models.racking.RailComponent.prototype.getFlashesList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Flash>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_flash_pb.Flash, 5));
};


/** @param {!Array<!proto.electrious.models.racking.Flash>} value */
proto.electrious.models.racking.RailComponent.prototype.setFlashesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.electrious.models.racking.Flash=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Flash}
 */
proto.electrious.models.racking.RailComponent.prototype.addFlashes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.electrious.models.racking.Flash, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailComponent.prototype.clearFlashesList = function() {
  this.setFlashesList([]);
};


/**
 * repeated LFoot lfeet = 6;
 * @return {!Array<!proto.electrious.models.racking.LFoot>}
 */
proto.electrious.models.racking.RailComponent.prototype.getLfeetList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.LFoot>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_lfoot_pb.LFoot, 6));
};


/** @param {!Array<!proto.electrious.models.racking.LFoot>} value */
proto.electrious.models.racking.RailComponent.prototype.setLfeetList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.electrious.models.racking.LFoot=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.LFoot}
 */
proto.electrious.models.racking.RailComponent.prototype.addLfeet = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.electrious.models.racking.LFoot, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailComponent.prototype.clearLfeetList = function() {
  this.setLfeetList([]);
};


/**
 * repeated Clamp clamps = 7;
 * @return {!Array<!proto.electrious.models.racking.Clamp>}
 */
proto.electrious.models.racking.RailComponent.prototype.getClampsList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Clamp>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_clamp_pb.Clamp, 7));
};


/** @param {!Array<!proto.electrious.models.racking.Clamp>} value */
proto.electrious.models.racking.RailComponent.prototype.setClampsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.electrious.models.racking.Clamp=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Clamp}
 */
proto.electrious.models.racking.RailComponent.prototype.addClamps = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.electrious.models.racking.Clamp, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailComponent.prototype.clearClampsList = function() {
  this.setClampsList([]);
};


/**
 * repeated Stopper stoppers = 8;
 * @return {!Array<!proto.electrious.models.racking.Stopper>}
 */
proto.electrious.models.racking.RailComponent.prototype.getStoppersList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Stopper>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_stopper_pb.Stopper, 8));
};


/** @param {!Array<!proto.electrious.models.racking.Stopper>} value */
proto.electrious.models.racking.RailComponent.prototype.setStoppersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.electrious.models.racking.Stopper=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Stopper}
 */
proto.electrious.models.racking.RailComponent.prototype.addStoppers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.electrious.models.racking.Stopper, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailComponent.prototype.clearStoppersList = function() {
  this.setStoppersList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.electrious.models.racking.RailFreeComponent.repeatedFields_ = [2,3,4,5,6,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.electrious.models.racking.RailFreeComponent.prototype.toObject = function(opt_includeInstance) {
  return proto.electrious.models.racking.RailFreeComponent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.electrious.models.racking.RailFreeComponent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.racking.RailFreeComponent.toObject = function(includeInstance, msg) {
  var obj = {
    arrayNumber: jspb.Message.getFieldWithDefault(msg, 1, 0),
    flashesList: jspb.Message.toObjectList(msg.getFlashesList(),
    electrious_models_racking_flash_pb.Flash.toObject, includeInstance),
    mountsList: jspb.Message.toObjectList(msg.getMountsList(),
    electrious_models_racking_mount_pb.Mount.toObject, includeInstance),
    bridgesList: jspb.Message.toObjectList(msg.getBridgesList(),
    electrious_models_racking_bridge_pb.Bridge.toObject, includeInstance),
    skirtsList: jspb.Message.toObjectList(msg.getSkirtsList(),
    electrious_models_racking_skirt_pb.Skirt.toObject, includeInstance),
    leftCapsList: jspb.Message.toObjectList(msg.getLeftCapsList(),
    electrious_models_racking_endcap_pb.EndCap.toObject, includeInstance),
    rightCapsList: jspb.Message.toObjectList(msg.getRightCapsList(),
    electrious_models_racking_endcap_pb.EndCap.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.electrious.models.racking.RailFreeComponent}
 */
proto.electrious.models.racking.RailFreeComponent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.electrious.models.racking.RailFreeComponent;
  return proto.electrious.models.racking.RailFreeComponent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.electrious.models.racking.RailFreeComponent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.electrious.models.racking.RailFreeComponent}
 */
proto.electrious.models.racking.RailFreeComponent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setArrayNumber(value);
      break;
    case 2:
      var value = new electrious_models_racking_flash_pb.Flash;
      reader.readMessage(value,electrious_models_racking_flash_pb.Flash.deserializeBinaryFromReader);
      msg.addFlashes(value);
      break;
    case 3:
      var value = new electrious_models_racking_mount_pb.Mount;
      reader.readMessage(value,electrious_models_racking_mount_pb.Mount.deserializeBinaryFromReader);
      msg.addMounts(value);
      break;
    case 4:
      var value = new electrious_models_racking_bridge_pb.Bridge;
      reader.readMessage(value,electrious_models_racking_bridge_pb.Bridge.deserializeBinaryFromReader);
      msg.addBridges(value);
      break;
    case 5:
      var value = new electrious_models_racking_skirt_pb.Skirt;
      reader.readMessage(value,electrious_models_racking_skirt_pb.Skirt.deserializeBinaryFromReader);
      msg.addSkirts(value);
      break;
    case 6:
      var value = new electrious_models_racking_endcap_pb.EndCap;
      reader.readMessage(value,electrious_models_racking_endcap_pb.EndCap.deserializeBinaryFromReader);
      msg.addLeftCaps(value);
      break;
    case 7:
      var value = new electrious_models_racking_endcap_pb.EndCap;
      reader.readMessage(value,electrious_models_racking_endcap_pb.EndCap.deserializeBinaryFromReader);
      msg.addRightCaps(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.electrious.models.racking.RailFreeComponent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.electrious.models.racking.RailFreeComponent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.electrious.models.racking.RailFreeComponent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.racking.RailFreeComponent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getArrayNumber();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getFlashesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      electrious_models_racking_flash_pb.Flash.serializeBinaryToWriter
    );
  }
  f = message.getMountsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      electrious_models_racking_mount_pb.Mount.serializeBinaryToWriter
    );
  }
  f = message.getBridgesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      electrious_models_racking_bridge_pb.Bridge.serializeBinaryToWriter
    );
  }
  f = message.getSkirtsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      electrious_models_racking_skirt_pb.Skirt.serializeBinaryToWriter
    );
  }
  f = message.getLeftCapsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      electrious_models_racking_endcap_pb.EndCap.serializeBinaryToWriter
    );
  }
  f = message.getRightCapsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      electrious_models_racking_endcap_pb.EndCap.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 array_number = 1;
 * @return {number}
 */
proto.electrious.models.racking.RailFreeComponent.prototype.getArrayNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.electrious.models.racking.RailFreeComponent.prototype.setArrayNumber = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated Flash flashes = 2;
 * @return {!Array<!proto.electrious.models.racking.Flash>}
 */
proto.electrious.models.racking.RailFreeComponent.prototype.getFlashesList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Flash>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_flash_pb.Flash, 2));
};


/** @param {!Array<!proto.electrious.models.racking.Flash>} value */
proto.electrious.models.racking.RailFreeComponent.prototype.setFlashesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.electrious.models.racking.Flash=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Flash}
 */
proto.electrious.models.racking.RailFreeComponent.prototype.addFlashes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.electrious.models.racking.Flash, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailFreeComponent.prototype.clearFlashesList = function() {
  this.setFlashesList([]);
};


/**
 * repeated Mount mounts = 3;
 * @return {!Array<!proto.electrious.models.racking.Mount>}
 */
proto.electrious.models.racking.RailFreeComponent.prototype.getMountsList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Mount>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_mount_pb.Mount, 3));
};


/** @param {!Array<!proto.electrious.models.racking.Mount>} value */
proto.electrious.models.racking.RailFreeComponent.prototype.setMountsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.electrious.models.racking.Mount=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Mount}
 */
proto.electrious.models.racking.RailFreeComponent.prototype.addMounts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.electrious.models.racking.Mount, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailFreeComponent.prototype.clearMountsList = function() {
  this.setMountsList([]);
};


/**
 * repeated Bridge bridges = 4;
 * @return {!Array<!proto.electrious.models.racking.Bridge>}
 */
proto.electrious.models.racking.RailFreeComponent.prototype.getBridgesList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Bridge>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_bridge_pb.Bridge, 4));
};


/** @param {!Array<!proto.electrious.models.racking.Bridge>} value */
proto.electrious.models.racking.RailFreeComponent.prototype.setBridgesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.electrious.models.racking.Bridge=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Bridge}
 */
proto.electrious.models.racking.RailFreeComponent.prototype.addBridges = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.electrious.models.racking.Bridge, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailFreeComponent.prototype.clearBridgesList = function() {
  this.setBridgesList([]);
};


/**
 * repeated Skirt skirts = 5;
 * @return {!Array<!proto.electrious.models.racking.Skirt>}
 */
proto.electrious.models.racking.RailFreeComponent.prototype.getSkirtsList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Skirt>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_skirt_pb.Skirt, 5));
};


/** @param {!Array<!proto.electrious.models.racking.Skirt>} value */
proto.electrious.models.racking.RailFreeComponent.prototype.setSkirtsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.electrious.models.racking.Skirt=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Skirt}
 */
proto.electrious.models.racking.RailFreeComponent.prototype.addSkirts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.electrious.models.racking.Skirt, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailFreeComponent.prototype.clearSkirtsList = function() {
  this.setSkirtsList([]);
};


/**
 * repeated EndCap left_caps = 6;
 * @return {!Array<!proto.electrious.models.racking.EndCap>}
 */
proto.electrious.models.racking.RailFreeComponent.prototype.getLeftCapsList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.EndCap>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_endcap_pb.EndCap, 6));
};


/** @param {!Array<!proto.electrious.models.racking.EndCap>} value */
proto.electrious.models.racking.RailFreeComponent.prototype.setLeftCapsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.electrious.models.racking.EndCap=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.EndCap}
 */
proto.electrious.models.racking.RailFreeComponent.prototype.addLeftCaps = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.electrious.models.racking.EndCap, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailFreeComponent.prototype.clearLeftCapsList = function() {
  this.setLeftCapsList([]);
};


/**
 * repeated EndCap right_caps = 7;
 * @return {!Array<!proto.electrious.models.racking.EndCap>}
 */
proto.electrious.models.racking.RailFreeComponent.prototype.getRightCapsList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.EndCap>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_endcap_pb.EndCap, 7));
};


/** @param {!Array<!proto.electrious.models.racking.EndCap>} value */
proto.electrious.models.racking.RailFreeComponent.prototype.setRightCapsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.electrious.models.racking.EndCap=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.EndCap}
 */
proto.electrious.models.racking.RailFreeComponent.prototype.addRightCaps = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.electrious.models.racking.EndCap, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailFreeComponent.prototype.clearRightCapsList = function() {
  this.setRightCapsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.electrious.models.racking.RailFlatComponent.repeatedFields_ = [2,4,5,6,7,8,9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.toObject = function(opt_includeInstance) {
  return proto.electrious.models.racking.RailFlatComponent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.electrious.models.racking.RailFlatComponent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.racking.RailFlatComponent.toObject = function(includeInstance, msg) {
  var obj = {
    arrayNumber: jspb.Message.getFieldWithDefault(msg, 1, 0),
    railsList: jspb.Message.toObjectList(msg.getRailsList(),
    electrious_models_racking_rail_pb.Rail.toObject, includeInstance),
    fullRailsNum: jspb.Message.getFieldWithDefault(msg, 3, 0),
    splicesList: jspb.Message.toObjectList(msg.getSplicesList(),
    electrious_models_racking_splice_pb.Splice.toObject, includeInstance),
    clampsList: jspb.Message.toObjectList(msg.getClampsList(),
    electrious_models_racking_clamp_pb.Clamp.toObject, includeInstance),
    stoppersList: jspb.Message.toObjectList(msg.getStoppersList(),
    electrious_models_racking_stopper_pb.Stopper.toObject, includeInstance),
    supportRailsList: jspb.Message.toObjectList(msg.getSupportRailsList(),
    electrious_models_racking_supportrail_pb.SupportRail.toObject, includeInstance),
    qbaseMountsList: jspb.Message.toObjectList(msg.getQbaseMountsList(),
    electrious_models_racking_qbasemount_pb.QBaseMount.toObject, includeInstance),
    tiltLegsList: jspb.Message.toObjectList(msg.getTiltLegsList(),
    electrious_models_racking_tiltleg_pb.TiltLeg.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.electrious.models.racking.RailFlatComponent}
 */
proto.electrious.models.racking.RailFlatComponent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.electrious.models.racking.RailFlatComponent;
  return proto.electrious.models.racking.RailFlatComponent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.electrious.models.racking.RailFlatComponent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.electrious.models.racking.RailFlatComponent}
 */
proto.electrious.models.racking.RailFlatComponent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setArrayNumber(value);
      break;
    case 2:
      var value = new electrious_models_racking_rail_pb.Rail;
      reader.readMessage(value,electrious_models_racking_rail_pb.Rail.deserializeBinaryFromReader);
      msg.addRails(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFullRailsNum(value);
      break;
    case 4:
      var value = new electrious_models_racking_splice_pb.Splice;
      reader.readMessage(value,electrious_models_racking_splice_pb.Splice.deserializeBinaryFromReader);
      msg.addSplices(value);
      break;
    case 5:
      var value = new electrious_models_racking_clamp_pb.Clamp;
      reader.readMessage(value,electrious_models_racking_clamp_pb.Clamp.deserializeBinaryFromReader);
      msg.addClamps(value);
      break;
    case 6:
      var value = new electrious_models_racking_stopper_pb.Stopper;
      reader.readMessage(value,electrious_models_racking_stopper_pb.Stopper.deserializeBinaryFromReader);
      msg.addStoppers(value);
      break;
    case 7:
      var value = new electrious_models_racking_supportrail_pb.SupportRail;
      reader.readMessage(value,electrious_models_racking_supportrail_pb.SupportRail.deserializeBinaryFromReader);
      msg.addSupportRails(value);
      break;
    case 8:
      var value = new electrious_models_racking_qbasemount_pb.QBaseMount;
      reader.readMessage(value,electrious_models_racking_qbasemount_pb.QBaseMount.deserializeBinaryFromReader);
      msg.addQbaseMounts(value);
      break;
    case 9:
      var value = new electrious_models_racking_tiltleg_pb.TiltLeg;
      reader.readMessage(value,electrious_models_racking_tiltleg_pb.TiltLeg.deserializeBinaryFromReader);
      msg.addTiltLegs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.electrious.models.racking.RailFlatComponent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.electrious.models.racking.RailFlatComponent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.racking.RailFlatComponent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getArrayNumber();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getRailsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      electrious_models_racking_rail_pb.Rail.serializeBinaryToWriter
    );
  }
  f = message.getFullRailsNum();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getSplicesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      electrious_models_racking_splice_pb.Splice.serializeBinaryToWriter
    );
  }
  f = message.getClampsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      electrious_models_racking_clamp_pb.Clamp.serializeBinaryToWriter
    );
  }
  f = message.getStoppersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      electrious_models_racking_stopper_pb.Stopper.serializeBinaryToWriter
    );
  }
  f = message.getSupportRailsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      electrious_models_racking_supportrail_pb.SupportRail.serializeBinaryToWriter
    );
  }
  f = message.getQbaseMountsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      electrious_models_racking_qbasemount_pb.QBaseMount.serializeBinaryToWriter
    );
  }
  f = message.getTiltLegsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      electrious_models_racking_tiltleg_pb.TiltLeg.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 array_number = 1;
 * @return {number}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.getArrayNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.electrious.models.racking.RailFlatComponent.prototype.setArrayNumber = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated Rail rails = 2;
 * @return {!Array<!proto.electrious.models.racking.Rail>}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.getRailsList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Rail>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_rail_pb.Rail, 2));
};


/** @param {!Array<!proto.electrious.models.racking.Rail>} value */
proto.electrious.models.racking.RailFlatComponent.prototype.setRailsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.electrious.models.racking.Rail=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Rail}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.addRails = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.electrious.models.racking.Rail, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailFlatComponent.prototype.clearRailsList = function() {
  this.setRailsList([]);
};


/**
 * optional int32 full_rails_num = 3;
 * @return {number}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.getFullRailsNum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.electrious.models.racking.RailFlatComponent.prototype.setFullRailsNum = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated Splice splices = 4;
 * @return {!Array<!proto.electrious.models.racking.Splice>}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.getSplicesList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Splice>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_splice_pb.Splice, 4));
};


/** @param {!Array<!proto.electrious.models.racking.Splice>} value */
proto.electrious.models.racking.RailFlatComponent.prototype.setSplicesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.electrious.models.racking.Splice=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Splice}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.addSplices = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.electrious.models.racking.Splice, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailFlatComponent.prototype.clearSplicesList = function() {
  this.setSplicesList([]);
};


/**
 * repeated Clamp clamps = 5;
 * @return {!Array<!proto.electrious.models.racking.Clamp>}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.getClampsList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Clamp>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_clamp_pb.Clamp, 5));
};


/** @param {!Array<!proto.electrious.models.racking.Clamp>} value */
proto.electrious.models.racking.RailFlatComponent.prototype.setClampsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.electrious.models.racking.Clamp=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Clamp}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.addClamps = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.electrious.models.racking.Clamp, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailFlatComponent.prototype.clearClampsList = function() {
  this.setClampsList([]);
};


/**
 * repeated Stopper stoppers = 6;
 * @return {!Array<!proto.electrious.models.racking.Stopper>}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.getStoppersList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Stopper>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_stopper_pb.Stopper, 6));
};


/** @param {!Array<!proto.electrious.models.racking.Stopper>} value */
proto.electrious.models.racking.RailFlatComponent.prototype.setStoppersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.electrious.models.racking.Stopper=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Stopper}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.addStoppers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.electrious.models.racking.Stopper, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailFlatComponent.prototype.clearStoppersList = function() {
  this.setStoppersList([]);
};


/**
 * repeated SupportRail support_rails = 7;
 * @return {!Array<!proto.electrious.models.racking.SupportRail>}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.getSupportRailsList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.SupportRail>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_supportrail_pb.SupportRail, 7));
};


/** @param {!Array<!proto.electrious.models.racking.SupportRail>} value */
proto.electrious.models.racking.RailFlatComponent.prototype.setSupportRailsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.electrious.models.racking.SupportRail=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.SupportRail}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.addSupportRails = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.electrious.models.racking.SupportRail, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailFlatComponent.prototype.clearSupportRailsList = function() {
  this.setSupportRailsList([]);
};


/**
 * repeated QBaseMount qbase_mounts = 8;
 * @return {!Array<!proto.electrious.models.racking.QBaseMount>}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.getQbaseMountsList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.QBaseMount>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_qbasemount_pb.QBaseMount, 8));
};


/** @param {!Array<!proto.electrious.models.racking.QBaseMount>} value */
proto.electrious.models.racking.RailFlatComponent.prototype.setQbaseMountsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.electrious.models.racking.QBaseMount=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.QBaseMount}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.addQbaseMounts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.electrious.models.racking.QBaseMount, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailFlatComponent.prototype.clearQbaseMountsList = function() {
  this.setQbaseMountsList([]);
};


/**
 * repeated TiltLeg tilt_legs = 9;
 * @return {!Array<!proto.electrious.models.racking.TiltLeg>}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.getTiltLegsList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.TiltLeg>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_tiltleg_pb.TiltLeg, 9));
};


/** @param {!Array<!proto.electrious.models.racking.TiltLeg>} value */
proto.electrious.models.racking.RailFlatComponent.prototype.setTiltLegsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.electrious.models.racking.TiltLeg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.TiltLeg}
 */
proto.electrious.models.racking.RailFlatComponent.prototype.addTiltLegs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.electrious.models.racking.TiltLeg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.RailFlatComponent.prototype.clearTiltLegsList = function() {
  this.setTiltLegsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.electrious.models.racking.BallastComponent.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.electrious.models.racking.BallastComponent.prototype.toObject = function(opt_includeInstance) {
  return proto.electrious.models.racking.BallastComponent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.electrious.models.racking.BallastComponent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.racking.BallastComponent.toObject = function(includeInstance, msg) {
  var obj = {
    arrayNumber: jspb.Message.getFieldWithDefault(msg, 1, 0),
    chassisList: jspb.Message.toObjectList(msg.getChassisList(),
    electrious_models_racking_chassis_pb.Chassis.toObject, includeInstance),
    blocksList: jspb.Message.toObjectList(msg.getBlocksList(),
    electrious_models_racking_block_pb.Block.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.electrious.models.racking.BallastComponent}
 */
proto.electrious.models.racking.BallastComponent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.electrious.models.racking.BallastComponent;
  return proto.electrious.models.racking.BallastComponent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.electrious.models.racking.BallastComponent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.electrious.models.racking.BallastComponent}
 */
proto.electrious.models.racking.BallastComponent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setArrayNumber(value);
      break;
    case 2:
      var value = new electrious_models_racking_chassis_pb.Chassis;
      reader.readMessage(value,electrious_models_racking_chassis_pb.Chassis.deserializeBinaryFromReader);
      msg.addChassis(value);
      break;
    case 3:
      var value = new electrious_models_racking_block_pb.Block;
      reader.readMessage(value,electrious_models_racking_block_pb.Block.deserializeBinaryFromReader);
      msg.addBlocks(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.electrious.models.racking.BallastComponent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.electrious.models.racking.BallastComponent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.electrious.models.racking.BallastComponent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.racking.BallastComponent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getArrayNumber();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getChassisList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      electrious_models_racking_chassis_pb.Chassis.serializeBinaryToWriter
    );
  }
  f = message.getBlocksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      electrious_models_racking_block_pb.Block.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 array_number = 1;
 * @return {number}
 */
proto.electrious.models.racking.BallastComponent.prototype.getArrayNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.electrious.models.racking.BallastComponent.prototype.setArrayNumber = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated Chassis chassis = 2;
 * @return {!Array<!proto.electrious.models.racking.Chassis>}
 */
proto.electrious.models.racking.BallastComponent.prototype.getChassisList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Chassis>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_chassis_pb.Chassis, 2));
};


/** @param {!Array<!proto.electrious.models.racking.Chassis>} value */
proto.electrious.models.racking.BallastComponent.prototype.setChassisList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.electrious.models.racking.Chassis=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Chassis}
 */
proto.electrious.models.racking.BallastComponent.prototype.addChassis = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.electrious.models.racking.Chassis, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.BallastComponent.prototype.clearChassisList = function() {
  this.setChassisList([]);
};


/**
 * repeated Block blocks = 3;
 * @return {!Array<!proto.electrious.models.racking.Block>}
 */
proto.electrious.models.racking.BallastComponent.prototype.getBlocksList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Block>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_block_pb.Block, 3));
};


/** @param {!Array<!proto.electrious.models.racking.Block>} value */
proto.electrious.models.racking.BallastComponent.prototype.setBlocksList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.electrious.models.racking.Block=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Block}
 */
proto.electrious.models.racking.BallastComponent.prototype.addBlocks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.electrious.models.racking.Block, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.BallastComponent.prototype.clearBlocksList = function() {
  this.setBlocksList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.electrious.models.racking.GAFComponent.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.electrious.models.racking.GAFComponent.prototype.toObject = function(opt_includeInstance) {
  return proto.electrious.models.racking.GAFComponent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.electrious.models.racking.GAFComponent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.racking.GAFComponent.toObject = function(includeInstance, msg) {
  var obj = {
    arrayNumber: jspb.Message.getFieldWithDefault(msg, 1, 0),
    hoodsList: jspb.Message.toObjectList(msg.getHoodsList(),
    electrious_models_racking_hood_pb.Hood.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.electrious.models.racking.GAFComponent}
 */
proto.electrious.models.racking.GAFComponent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.electrious.models.racking.GAFComponent;
  return proto.electrious.models.racking.GAFComponent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.electrious.models.racking.GAFComponent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.electrious.models.racking.GAFComponent}
 */
proto.electrious.models.racking.GAFComponent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setArrayNumber(value);
      break;
    case 2:
      var value = new electrious_models_racking_hood_pb.Hood;
      reader.readMessage(value,electrious_models_racking_hood_pb.Hood.deserializeBinaryFromReader);
      msg.addHoods(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.electrious.models.racking.GAFComponent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.electrious.models.racking.GAFComponent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.electrious.models.racking.GAFComponent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.racking.GAFComponent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getArrayNumber();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getHoodsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      electrious_models_racking_hood_pb.Hood.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 array_number = 1;
 * @return {number}
 */
proto.electrious.models.racking.GAFComponent.prototype.getArrayNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.electrious.models.racking.GAFComponent.prototype.setArrayNumber = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated Hood hoods = 2;
 * @return {!Array<!proto.electrious.models.racking.Hood>}
 */
proto.electrious.models.racking.GAFComponent.prototype.getHoodsList = function() {
  return /** @type{!Array<!proto.electrious.models.racking.Hood>} */ (
    jspb.Message.getRepeatedWrapperField(this, electrious_models_racking_hood_pb.Hood, 2));
};


/** @param {!Array<!proto.electrious.models.racking.Hood>} value */
proto.electrious.models.racking.GAFComponent.prototype.setHoodsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.electrious.models.racking.Hood=} opt_value
 * @param {number=} opt_index
 * @return {!proto.electrious.models.racking.Hood}
 */
proto.electrious.models.racking.GAFComponent.prototype.addHoods = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.electrious.models.racking.Hood, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.electrious.models.racking.GAFComponent.prototype.clearHoodsList = function() {
  this.setHoodsList([]);
};


goog.object.extend(exports, proto.electrious.models.racking);
