/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var electrious_uuid_pb = require('../../../electrious/uuid_pb.js');
goog.object.extend(proto, electrious_uuid_pb);
goog.exportSymbol('proto.electrious.models.racking.Flash', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.electrious.models.racking.Flash = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.electrious.models.racking.Flash, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.electrious.models.racking.Flash.displayName = 'proto.electrious.models.racking.Flash';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.electrious.models.racking.Flash.prototype.toObject = function(opt_includeInstance) {
  return proto.electrious.models.racking.Flash.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.electrious.models.racking.Flash} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.racking.Flash.toObject = function(includeInstance, msg) {
  var obj = {
    id: (f = msg.getId()) && electrious_uuid_pb.UUID.toObject(includeInstance, f),
    arrayNumber: jspb.Message.getFieldWithDefault(msg, 2, 0),
    rafterId: (f = msg.getRafterId()) && electrious_uuid_pb.UUID.toObject(includeInstance, f),
    clampTarget: +jspb.Message.getFieldWithDefault(msg, 4, 0.0),
    x: +jspb.Message.getFieldWithDefault(msg, 5, 0.0),
    y: +jspb.Message.getFieldWithDefault(msg, 6, 0.0),
    z: +jspb.Message.getFieldWithDefault(msg, 7, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.electrious.models.racking.Flash}
 */
proto.electrious.models.racking.Flash.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.electrious.models.racking.Flash;
  return proto.electrious.models.racking.Flash.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.electrious.models.racking.Flash} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.electrious.models.racking.Flash}
 */
proto.electrious.models.racking.Flash.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new electrious_uuid_pb.UUID;
      reader.readMessage(value,electrious_uuid_pb.UUID.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setArrayNumber(value);
      break;
    case 3:
      var value = new electrious_uuid_pb.UUID;
      reader.readMessage(value,electrious_uuid_pb.UUID.deserializeBinaryFromReader);
      msg.setRafterId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setClampTarget(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setX(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setY(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setZ(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.electrious.models.racking.Flash.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.electrious.models.racking.Flash.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.electrious.models.racking.Flash} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.models.racking.Flash.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      electrious_uuid_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getArrayNumber();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getRafterId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      electrious_uuid_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getClampTarget();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getX();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getZ();
  if (f !== 0.0) {
    writer.writeDouble(
      7,
      f
    );
  }
};


/**
 * optional electrious.UUID id = 1;
 * @return {?proto.electrious.UUID}
 */
proto.electrious.models.racking.Flash.prototype.getId = function() {
  return /** @type{?proto.electrious.UUID} */ (
    jspb.Message.getWrapperField(this, electrious_uuid_pb.UUID, 1));
};


/** @param {?proto.electrious.UUID|undefined} value */
proto.electrious.models.racking.Flash.prototype.setId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.electrious.models.racking.Flash.prototype.clearId = function() {
  this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.electrious.models.racking.Flash.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 array_number = 2;
 * @return {number}
 */
proto.electrious.models.racking.Flash.prototype.getArrayNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.electrious.models.racking.Flash.prototype.setArrayNumber = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional electrious.UUID rafter_id = 3;
 * @return {?proto.electrious.UUID}
 */
proto.electrious.models.racking.Flash.prototype.getRafterId = function() {
  return /** @type{?proto.electrious.UUID} */ (
    jspb.Message.getWrapperField(this, electrious_uuid_pb.UUID, 3));
};


/** @param {?proto.electrious.UUID|undefined} value */
proto.electrious.models.racking.Flash.prototype.setRafterId = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.electrious.models.racking.Flash.prototype.clearRafterId = function() {
  this.setRafterId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.electrious.models.racking.Flash.prototype.hasRafterId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional double clamp_target = 4;
 * @return {number}
 */
proto.electrious.models.racking.Flash.prototype.getClampTarget = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.electrious.models.racking.Flash.prototype.setClampTarget = function(value) {
  jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double x = 5;
 * @return {number}
 */
proto.electrious.models.racking.Flash.prototype.getX = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 5, 0.0));
};


/** @param {number} value */
proto.electrious.models.racking.Flash.prototype.setX = function(value) {
  jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional double y = 6;
 * @return {number}
 */
proto.electrious.models.racking.Flash.prototype.getY = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 6, 0.0));
};


/** @param {number} value */
proto.electrious.models.racking.Flash.prototype.setY = function(value) {
  jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional double z = 7;
 * @return {number}
 */
proto.electrious.models.racking.Flash.prototype.getZ = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 7, 0.0));
};


/** @param {number} value */
proto.electrious.models.racking.Flash.prototype.setZ = function(value) {
  jspb.Message.setProto3FloatField(this, 7, value);
};


goog.object.extend(exports, proto.electrious.models.racking);
