/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var electrious_models_file_pb = require('../../../electrious/models/file_pb.js');
goog.object.extend(proto, electrious_models_file_pb);
goog.exportSymbol('proto.electrious.workers.roofplatedet.Request', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.electrious.workers.roofplatedet.Request = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.electrious.workers.roofplatedet.Request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.electrious.workers.roofplatedet.Request.displayName = 'proto.electrious.workers.roofplatedet.Request';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.electrious.workers.roofplatedet.Request.prototype.toObject = function(opt_includeInstance) {
  return proto.electrious.workers.roofplatedet.Request.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.electrious.workers.roofplatedet.Request} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.workers.roofplatedet.Request.toObject = function(includeInstance, msg) {
  var obj = {
    ply: (f = msg.getPly()) && electrious_models_file_pb.File.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.electrious.workers.roofplatedet.Request}
 */
proto.electrious.workers.roofplatedet.Request.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.electrious.workers.roofplatedet.Request;
  return proto.electrious.workers.roofplatedet.Request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.electrious.workers.roofplatedet.Request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.electrious.workers.roofplatedet.Request}
 */
proto.electrious.workers.roofplatedet.Request.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new electrious_models_file_pb.File;
      reader.readMessage(value,electrious_models_file_pb.File.deserializeBinaryFromReader);
      msg.setPly(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.electrious.workers.roofplatedet.Request.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.electrious.workers.roofplatedet.Request.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.electrious.workers.roofplatedet.Request} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.electrious.workers.roofplatedet.Request.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPly();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      electrious_models_file_pb.File.serializeBinaryToWriter
    );
  }
};


/**
 * optional electrious.models.File ply = 2;
 * @return {?proto.electrious.models.File}
 */
proto.electrious.workers.roofplatedet.Request.prototype.getPly = function() {
  return /** @type{?proto.electrious.models.File} */ (
    jspb.Message.getWrapperField(this, electrious_models_file_pb.File, 2));
};


/** @param {?proto.electrious.models.File|undefined} value */
proto.electrious.workers.roofplatedet.Request.prototype.setPly = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.electrious.workers.roofplatedet.Request.prototype.clearPly = function() {
  this.setPly(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.electrious.workers.roofplatedet.Request.prototype.hasPly = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.electrious.workers.roofplatedet);
